=== radiowarwick/digiplay_legacy/doc/dps.dtd
<!-- DTD for RaW Digital Playout System -->
<!ELEMENT audio (album,segment?)>
	<!ATTLIST audio md5 CDATA #REQUIRED>
	<!ATTLIST audio type (music|jingle|advert|prerec) #REQUIRED>
	<!ATTLIST audio creation_date CDATA #IMPLIED>
	<!ATTLIST audio user CDATA #IMPLIED>
	<!ELEMENT album EMPTY>
		<!ATTLIST album name CDATA #REQUIRED>
		<!ATTLIST album origin CDATA #REQUIRED>
		<!ATTLIST album released CDATA #IMPLIED>
		<!ATTLIST album reclibid CDATA #IMPLIED>
	<!ELEMENT segment (title,artist+,jingle?,advert?,smpl,classification?)>
		<!ELEMENT title (#PCDATA)>
		<!ELEMENT artist (role*,keyword*)>
			<!ATTLIST artist name CDATA #REQUIRED>
			<!ATTLIST artist true_name CDATA #IMPLIED>
			<!ELEMENT role (#PCDATA)>
			<!ELEMENT keyword (#PCDATA)>
		<!ELEMENT jingle (package+)>
			<!ATTLIST jingle type (generic|idents|contact|news|shows) #REQUIRED>
			<!ELEMENT package EMPTY>
				<!ATTLIST package name CDATA #REQUIRED>
				<!ATTLIST package description CDATA #IMPLIED>
		<!ELEMENT advert EMPTY>
			<!ATTLIST advert company CDATA #REQUIRED>
			<!ATTLIST advert description CDATA #IMPLIED>
		<!ELEMENT smpl EMPTY>
			<!ATTLIST smpl length CDATA #REQUIRED>
			<!ATTLIST smpl trim_start CDATA #REQUIRED>
			<!ATTLIST smpl trim_end CDATA #REQUIRED>
			<!ATTLIST smpl fade_in CDATA #REQUIRED>
			<!ATTLIST smpl fade_out CDATA #REQUIRED>
		<!ELEMENT classification (volume?,speed?,mood?,keyword*)>
			<!ATTLIST classification volume CDATA #IMPLIED>
			<!ATTLIST classification speed CDATA #IMPLIED>
			<!ATTLIST classification mood CDATA #IMPLIED>
			<!ATTLIST classification censor (yes|no) "no">
			<!ELEMENT keyword (#PCDATA)>

=== radiowarwick/digiplay_legacy/share/doc/examples/sample2.xml
<!-- Sample XML layout for a ripped CD track -->
<?xml version="1.0"?>
<!DOCTYPE audio_v1 SYSTEM "dps.dtd">

<audio md5="0123456789abcdef0123456789abcdef" 
		type="user"
		creation_date="2005-12-25">
	<album name="Interviews - Cast from 'A Christmas Story'"
			origin="field" />
	<segment>
		<title>Interview with Santa</title>
	    <artist name="Santa Claus">
			<role>Interviewee</role>
			<keyword>Fat</keyword>
			<keyword>Beard</keyword>
		</artist>
		<artist name="Guess">
			<role>Interviewer</role>
			<keyword>Fit</keyword>
			<keyword>Beardless</keyword>
		</artist>
		<artist name="Little Jimmy the Elf">
			<role>Gimp trying to get on the radio</role>
			<keyword>Annoying</keyword>
			<keyword>Loud</keyword>
			<keyword>Brick</keyword>
			<keyword>Dead</keyword>
		</artist>
		<smpl length="105263" 
				trim_start="200" 
				trim_end="105200" 
				fade_in="200" 
				fade_out="105263" />
	</segment>
	<segment>
		<title>Interview with Rudolph</title>
		<artist name="Rudolph">
			<role>Interviewee</role>
			<keyword>Reindeer</keyword>
			<keyword>Red_Nose</keyword>
		</artist>
		<artist name="Mmmmmmmmm">
			<role>Distraction...erm, interviewer</role>
			<keyword>Tasty</keyword>
		</artist>
		<smpl length="256096"
			trim_start="105300"
			trim_end="240600"
			fade_in="105300"
			fade_out="240600" />
	</segment>
</audio>
